@startuml ToBeContext
title Медикаменте To Be Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(doctor, "Специалист-медик", "Оказывает медицинские услуги")
Person(administrator, "Сотрудник ресепшена", "Ведет журнал записей к специалистам и заключает клиентские контракты")
Person(bookkeeper, "Бухгалтер", "Занимается процессингом платежей и ведет бухгалтерию, которая связана с учётом кадров, выплатой зарплат и налогами")
Person(warehouse, "Сотрудник склада", "Ведет учёт ТМЦ и закупок оборудования для медицинских кабинетов")
Person(cassier, "Кассир", "Принимает платежи")
Person(patient, "Пациент", "Получает медицинские услуги")
Person(businessanalyst, "Бизнес-аналитик Медикаменте", "Подготавливает аналитику в различных разрезах")


System(accounting, "1С Бухгалтерия предприятия", "Бухгалтерская система учёта")
System(wms, "1C Торговля и склад", "Складская система учёта")
System(acquiring, "ККМ", "Контрольно-кассовая машина")
System(mis, "Медицинская инфомационная система", "Журналы приема, медицинские заключения")
System(crm,"CRM","Сбор данных о клиенте, хранение и распространение ClientID")

System(mobile_mis, "Мобильное приложение ЛК МИС", "доступ с мобильного устройства к функциональности МИС для пациентов")
System(clientportal, "Клиентский портал", "Web-портал клиента")
System(administratorportal, "Портал сотдруника ресепшена", "Web-портал сотрудника ресепшена")
System(paymentprocessing, "Платежный шлюз", "Обработка платежей")

System(s3, "Единое хранилище данных", "Хранение данных компании")
System(etl, "Сервис анонимизации данных","Обфускация и обезличивание данных из систем")
System(analytics, "Аналитическая платформа", "Набор BI, AI и ML инстументов для формирования аналитики и построения визуальных представлений")
System(apigateway, "API-шлюз", "Передача информации внешним потребителям")
System(exchangemailserver, "ExchangeMailServer", "Почтовый сервис внутренней почты")

System(DLP, "Система обнаружения утечек", "Фильтрация исходящих сообщений сотдруников Медикаменте")
System(audit, "Единая система аудита событий", "Запись действий пользователей и фактов работы с документами")
System(monitoring, "Единая система мониторинга и алертинга", "Запись ИТ и ИБ событий")
System(releasecontrol, "Система хранения и проверки релизов", "Проверка релизов (включая корректность работы с PII,PHI и пр.)")

System_Ext(laboratory, "Медицинская лаборатория", "Обработка анализов, предоставление отчетов")
System_Ext(bank, "Банк", "Обработка платежей")

Rel(crm,mis,"RBAC,\n Передача данных о клиенте")
Rel(mis,mobile_mis,"ClientID,\n Передача медицинской информации")
Rel(mis,clientportal,"ClientID,\n Передача медицинской информации")
Rel(accounting,wms,"Обновление складских остатков")
Rel(acquiring,bank, "SSL, TLS,\n Проведение оплаты")
Rel(mis,administratorportal,"RBAC,\n информация для консультации пациентов")
Rel(mis,s3, "RBAC,\n Хранение результатов анализов")
Rel(accounting,s3, "RBAC,\n Хранение скан-копий договоров и согласий")

Rel(clientportal,paymentprocessing, "SSL, TLS,\n Оплата медицинских услуг")
Rel(accounting,paymentprocessing,"SSL, TLS,\n Заявка на платеж")
Rel(paymentprocessing,bank,"SSL, TLS,\n Проведение оплаты")
Rel(mis,etl,"PII, PHI\n Поставка данных")
Rel(accounting,etl,"Поставка данных в аналитическую платформу")
Rel(wms,etl,"Поставка первичных данных в аналитическую платформу")
Rel(etl,analytics,"Поставка анонимизированных данных")
Rel(etl,apigateway, "Поставка анонимизированных данных")
Rel(etl,accounting, "Поставка анонимизированных данных")
Rel(apigateway,laboratory,"Отправка анонимизированных данных в лаборатории")

Rel(exchangemailserver,DLP,"Контроль за нераспространением утечек информации")
Rel(mis,DLP,"Контроль за нераспространением утечек информации")
Rel(mis,audit,"PII, PHI \n Сбор действий пользователей и работы с файлами, имеющими тег")
Rel(accounting,audit,"Сбор действий пользователей и работы с файлами, имеющими тег")
Rel(administratorportal,audit,"PII, PHI \n Сбор действий пользователей и работы с файлами, имеющими тег")
Rel(wms,audit,"Сбор действий пользователей и работы с файлами, имеющими тег")
Rel(paymentprocessing,audit,"Сбор действий пользователей и работы с файлами, имеющими тег")

Rel(audit,etl,"PII, PHI \n Анонимизация логов от чувствительной информации")
Rel(etl,monitoring, "Передача анонимизированных лог-файлов")
Rel(releasecontrol,monitoring,"Передача информации о фактах проверки релиза")

Rel(doctor,mis,"RBAC, \n Оказание медицинских услуг")
Rel(administrator,administratorportal,"RBAC, ClientID, \n Запрос к карточке клиента")
Rel(bookkeeper,accounting, "RBAC, \n Проведение платежей и учет операций")
Rel(warehouse,wms, "RBAC, \n Работа со складскими остатками")
Rel(cassier,acquiring,"RBAC, \n Проведение платежей")
Rel(patient,mobile_mis,"ClientID, \n Оказание медицинских услуг")
Rel(businessanalyst,analytics,"Аналитическая работа с анонимизированными данными")

@enduml
